//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwndExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDemographic
    {
        public CustomerDemographic()
        {
            this.CustomerCustomerDemoes = new HashSet<CustomerCustomerDemo>();
        }
    
        public string CustomerTypeID { get; set; }
        public string CustomerDesc { get; set; }
    
        public virtual ICollection<CustomerCustomerDemo> CustomerCustomerDemoes { get; set; }
    }
}
