//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwndExplorer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCustomerDemo
    {
        public string CustomerID { get; set; }
        public string CustomerTypeID { get; set; }
        public int ClusteredId { get; set; }
    
        public virtual CustomerDemographic CustomerDemographic { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
